import os
import sys
os.system("clear") 
os.system("git pull") 
os.system("clear") 
print("")
print("")
print("")
print("\tSorry,infect command has expired")
print("") 
print("\new update cmd coming soon") 
print("")
print("\t Contact me for more detail") 
print("")
os.system("xdg-open https://www.facebook.com/techabm") 
